export type Strategy = 'rss' | 'html'
export type SourceLevel = 'federal' | 'state' | 'ngo' | 'international' | 'sport'
export type Zone = 'south_west' | 'south_south' | 'south_east' | 'north_central' | 'north_west' | 'north_east'

export interface Source {
  name:       string
  url:        string
  pressPath:  string
  feedUrl?:   string
  tier:       1 | 2 | 3
  level:      SourceLevel
  category:   string
  zone?:      Zone
  strategy:   Strategy
  selector:   string
  active:     boolean
}

const sources: Source[] = [
  // ── TIER 1: Most critical — checked every 2 hours ───────────────────────────

  // Federal — Presidency & Core
  {
    name: 'State House (Presidency)',
    url: 'https://statehouse.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'federal', category: 'politics',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2.title a',
    active: true,
  },
  {
    name: 'Presidency',
    url: 'https://presidency.gov.ng',
    pressPath: '/press-release/',
    tier: 1, level: 'federal', category: 'politics',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Central Bank of Nigeria',
    url: 'https://www.cbn.gov.ng',
    pressPath: '/out/pressrelease.aspx',
    feedUrl: 'https://www.cbn.gov.ng/rss/pressrelease.xml',
    tier: 1, level: 'federal', category: 'economy',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'National Bureau of Statistics',
    url: 'https://nigerianstat.gov.ng',
    pressPath: '/news',
    tier: 1, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'INEC',
    url: 'https://www.inec.gov.ng',
    pressPath: '/press-releases/',
    tier: 1, level: 'federal', category: 'politics',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .views-row a',
    active: true,
  },
  {
    name: 'EFCC',
    url: 'https://efcc.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Nigeria Police Force',
    url: 'https://www.npf.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'NCDC',
    url: 'https://ncdc.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'federal', category: 'healthcare',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Federal Ministry of Finance',
    url: 'https://finance.gov.ng',
    pressPath: '/press-releases/',
    tier: 1, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'NNPC Limited',
    url: 'https://www.nnpcgroup.com',
    pressPath: '/Media/MediaReleases',
    tier: 1, level: 'federal', category: 'economy',
    strategy: 'html', selector: '.media-release a, article h2 a, h3 a',
    active: true,
  },
  {
    name: 'Budget Office of the Federation',
    url: 'https://www.budgetoffice.gov.ng',
    pressPath: '/index.php/news',
    tier: 1, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .news-item a',
    active: true,
  },
  {
    name: 'National Assembly',
    url: 'https://nass.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'federal', category: 'politics',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3.entry-title a',
    active: true,
  },

  // Tier 1 States — highest news volume
  {
    name: 'Lagos State Government',
    url: 'https://lagosstate.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'state', category: 'nigeria', zone: 'south_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Abuja / FCT Administration',
    url: 'https://fcta.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'state', category: 'nigeria', zone: 'north_central',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Rivers State Government',
    url: 'https://rivers.gov.ng',
    pressPath: '/news/',
    tier: 1, level: 'state', category: 'nigeria', zone: 'south_south',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },

  // ── TIER 2: Checked 3× daily (6am, 12pm, 6pm UTC) ───────────────────────────

  // Federal Ministries
  {
    name: 'Ministry of Health & Social Welfare',
    url: 'https://health.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'healthcare',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Ministry of Education',
    url: 'https://education.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'education',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Ministry of Agriculture & Food Security',
    url: 'https://fmard.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Ministry of Works',
    url: 'https://works.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Ministry of Trade & Investment',
    url: 'https://mti.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Ministry of Justice',
    url: 'https://justice.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Ministry of Petroleum Resources',
    url: 'https://petroleum.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Ministry of Defence',
    url: 'https://mod.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'NITDA',
    url: 'https://nitda.gov.ng',
    pressPath: '/news/',
    feedUrl: 'https://nitda.gov.ng/feed/',
    tier: 2, level: 'federal', category: 'technology',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'Ministry of Foreign Affairs',
    url: 'https://foreignaffairs.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'world',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Ministry of Humanitarian Affairs',
    url: 'https://humanitarian.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Ministry of Power',
    url: 'https://power.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Ministry of Transportation',
    url: 'https://transportation.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Ministry of Water Resources',
    url: 'https://waterresources.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },

  // Key Federal Agencies
  {
    name: 'ICPC',
    url: 'https://icpc.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Securities & Exchange Commission',
    url: 'https://sec.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Nigeria Communications Commission',
    url: 'https://www.ncc.gov.ng',
    pressPath: '/media-centre/press-releases/',
    feedUrl: 'https://www.ncc.gov.ng/feed/',
    tier: 2, level: 'federal', category: 'technology',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'Federal Inland Revenue Service',
    url: 'https://firs.gov.ng',
    pressPath: '/press-release/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'NAFDAC',
    url: 'https://www.nafdac.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'healthcare',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Debt Management Office',
    url: 'https://www.dmo.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Nigerian Army',
    url: 'https://army.mil.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Nigerian Navy',
    url: 'https://navy.mil.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Nigerian Air Force',
    url: 'https://airforce.mil.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'NUPRC (Upstream Petroleum)',
    url: 'https://nuprc.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Nigerian Electricity Regulatory Commission',
    url: 'https://nerc.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'National Health Insurance Authority',
    url: 'https://nhia.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'healthcare',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Supreme Court of Nigeria',
    url: 'https://supremecourt.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },

  // Tier 2 States — major population + political significance
  {
    name: 'Kano State Government',
    url: 'https://kano.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'north_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Kaduna State Government',
    url: 'https://kdsg.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'north_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Oyo State Government',
    url: 'https://oyostate.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Ogun State Government',
    url: 'https://ogunstate.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Anambra State Government',
    url: 'https://anostate.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Delta State Government',
    url: 'https://deltastate.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_south',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Edo State Government',
    url: 'https://edostate.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_south',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Enugu State Government',
    url: 'https://enugu.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Akwa Ibom State Government',
    url: 'https://akwaibomstate.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_south',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Cross River State Government',
    url: 'https://crossriverstate.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'south_south',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Plateau State Government',
    url: 'https://plateau.gov.ng',
    pressPath: '/news/',
    tier: 2, level: 'state', category: 'nigeria', zone: 'north_central',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },

  // NGOs
  {
    name: 'BudgIT',
    url: 'https://yourbudgit.com',
    pressPath: '/blog/',
    feedUrl: 'https://yourbudgit.com/feed/',
    tier: 2, level: 'ngo', category: 'economy',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'SERAP Nigeria',
    url: 'https://serap-nigeria.org',
    pressPath: '/press-releases/',
    feedUrl: 'https://serap-nigeria.org/feed/',
    tier: 2, level: 'ngo', category: 'nigeria',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'Enough is Enough Nigeria',
    url: 'https://eenonline.org',
    pressPath: '/news/',
    feedUrl: 'https://eenonline.org/feed/',
    tier: 2, level: 'ngo', category: 'nigeria',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'Civil Society Legislative Advocacy Centre',
    url: 'https://cislacnigeria.net',
    pressPath: '/news/',
    tier: 2, level: 'ngo', category: 'politics',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Amnesty International Nigeria',
    url: 'https://www.amnesty.org',
    pressPath: '/en/location/africa/west-and-central-africa/nigeria/news/',
    feedUrl: 'https://www.amnesty.org/en/location/africa/west-and-central-africa/nigeria/news/rss.xml',
    tier: 2, level: 'ngo', category: 'nigeria',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'Policy and Legal Advocacy Centre',
    url: 'https://placng.org',
    pressPath: '/i/',
    feedUrl: 'https://placng.org/i/feed/',
    tier: 2, level: 'ngo', category: 'politics',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'Paradigm Initiative',
    url: 'https://paradigmhq.org',
    pressPath: '/news/',
    feedUrl: 'https://paradigmhq.org/feed/',
    tier: 2, level: 'ngo', category: 'technology',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'Media Rights Agenda',
    url: 'https://mediarightsagenda.org',
    pressPath: '/news/',
    feedUrl: 'https://mediarightsagenda.org/feed/',
    tier: 2, level: 'ngo', category: 'nigeria',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'CLEEN Foundation',
    url: 'https://cleen.org',
    pressPath: '/news/',
    feedUrl: 'https://cleen.org/feed/',
    tier: 2, level: 'ngo', category: 'nigeria',
    strategy: 'rss', selector: '',
    active: true,
  },

  // International — public domain & intergovernmental sources only (no copyright risk)

  // US Government — fully public domain
  {
    name: 'Voice of America Africa',
    url: 'https://www.voanews.com',
    pressPath: '',
    feedUrl: 'https://www.voanews.com/api/zmsriqe_eit',
    tier: 2, level: 'international', category: 'world',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'USAID Africa',
    url: 'https://www.usaid.gov',
    pressPath: '/news-information/press-releases',
    tier: 2, level: 'international', category: 'world',
    strategy: 'html', selector: 'h3.teaser__title a, .views-row h3 a, article h3 a',
    active: true,
  },

  // UN System — public domain
  {
    name: 'UN News Africa',
    url: 'https://news.un.org',
    pressPath: '',
    feedUrl: 'https://news.un.org/feed/subscribe/en/news/region/africa/feed/rss.xml',
    tier: 2, level: 'international', category: 'world',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'UNICEF Press Releases',
    url: 'https://www.unicef.org',
    pressPath: '',
    feedUrl: 'https://www.unicef.org/press-releases/rss.xml',
    tier: 2, level: 'international', category: 'healthcare',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'UNDP Newsroom',
    url: 'https://www.undp.org',
    pressPath: '',
    feedUrl: 'https://www.undp.org/press-releases/rss.xml',
    tier: 2, level: 'international', category: 'world',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'World Food Programme',
    url: 'https://www.wfp.org',
    pressPath: '',
    feedUrl: 'https://www.wfp.org/rss.xml',
    tier: 2, level: 'international', category: 'healthcare',
    strategy: 'rss', selector: '',
    active: true,
  },

  // ── TIER 3: Checked once daily (6am UTC) ────────────────────────────────────

  // Remaining 25 States
  {
    name: 'Abia State Government',
    url: 'https://abia.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'south_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Adamawa State Government',
    url: 'https://adamawa.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Bauchi State Government',
    url: 'https://bauchi.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Bayelsa State Government',
    url: 'https://bayelsa.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'south_south',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Benue State Government',
    url: 'https://benue.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_central',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Borno State Government',
    url: 'https://borno.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Ebonyi State Government',
    url: 'https://ebonyi.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'south_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Ekiti State Government',
    url: 'https://ekitistate.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'south_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Gombe State Government',
    url: 'https://gombe.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Imo State Government',
    url: 'https://imo.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'south_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Jigawa State Government',
    url: 'https://jigawa.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Katsina State Government',
    url: 'https://katsina.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Kebbi State Government',
    url: 'https://kebbi.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Kogi State Government',
    url: 'https://kogistate.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_central',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Kwara State Government',
    url: 'https://kwarastate.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_central',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Nasarawa State Government',
    url: 'https://nasarawastate.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_central',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Niger State Government',
    url: 'https://nigerstate.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_central',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Ondo State Government',
    url: 'https://ondostate.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'south_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Osun State Government',
    url: 'https://osun.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'south_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Sokoto State Government',
    url: 'https://sokoto.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Taraba State Government',
    url: 'https://taraba.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Yobe State Government',
    url: 'https://yobe.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_east',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Zamfara State Government',
    url: 'https://zamfara.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'state', category: 'nigeria', zone: 'north_west',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },

  // Additional Federal Agencies
  {
    name: 'Nigerian Ports Authority',
    url: 'https://nigerianports.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Federal Road Safety Corps',
    url: 'https://frsc.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Nigerian Immigration Service',
    url: 'https://immigration.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'National Agency for the Prohibition of Trafficking in Persons',
    url: 'https://naptip.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Nigerian Meteorological Agency',
    url: 'https://nimet.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'National Emergency Management Agency',
    url: 'https://nema.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Corporate Affairs Commission',
    url: 'https://cac.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'National Universities Commission',
    url: 'https://nuc.edu.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'education',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Nigerian Investment Promotion Commission',
    url: 'https://nipc.gov.ng',
    pressPath: '/news/',
    tier: 3, level: 'federal', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },

  // More NGOs
  {
    name: 'NOIPolls',
    url: 'https://www.noi-polls.com',
    pressPath: '/press-releases/',
    tier: 3, level: 'ngo', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Nigeria Labour Congress',
    url: 'https://nlcng.org',
    pressPath: '/news/',
    tier: 3, level: 'ngo', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Trade Union Congress',
    url: 'https://tucnigeria.org',
    pressPath: '/news/',
    tier: 3, level: 'ngo', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },
  {
    name: 'Nigerian Bar Association',
    url: 'https://nigerianbar.org.ng',
    pressPath: '/news/',
    tier: 3, level: 'ngo', category: 'nigeria',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },
  {
    name: 'Nigerian Medical Association',
    url: 'https://nma.org.ng',
    pressPath: '/news/',
    tier: 3, level: 'ngo', category: 'healthcare',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h2 a',
    active: true,
  },
  {
    name: 'Manufacturers Association of Nigeria',
    url: 'https://manufacturersnigeria.org',
    pressPath: '/news/',
    tier: 3, level: 'ngo', category: 'economy',
    strategy: 'html', selector: 'article h2 a, .entry-title a, .post-title a',
    active: true,
  },

  // More International — public domain only
  {
    name: 'WHO Africa',
    url: 'https://www.afro.who.int',
    pressPath: '',
    feedUrl: 'https://www.afro.who.int/rss.xml',
    tier: 3, level: 'international', category: 'healthcare',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'African Development Bank',
    url: 'https://www.afdb.org',
    pressPath: '',
    feedUrl: 'https://www.afdb.org/en/rss-feeds/news',
    tier: 3, level: 'international', category: 'economy',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'UNHCR Africa',
    url: 'https://www.unhcr.org',
    pressPath: '',
    feedUrl: 'https://www.unhcr.org/news/rss.xml',
    tier: 3, level: 'international', category: 'world',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'ILO Newsroom',
    url: 'https://www.ilo.org',
    pressPath: '',
    feedUrl: 'https://www.ilo.org/global/about-the-ilo/newsroom/news/lang--en/rss/WCMS_007992/flyer.xml',
    tier: 3, level: 'international', category: 'economy',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'World Bank Africa',
    url: 'https://www.worldbank.org',
    pressPath: '',
    feedUrl: 'https://www.worldbank.org/en/region/afr/rss.xml',
    tier: 3, level: 'international', category: 'economy',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'IMF Press Releases',
    url: 'https://www.imf.org',
    pressPath: '',
    feedUrl: 'https://www.imf.org/en/News/rss?RSSFeedType=press',
    tier: 3, level: 'international', category: 'economy',
    strategy: 'rss', selector: '',
    active: true,
  },
  {
    name: 'African Union',
    url: 'https://au.int',
    pressPath: '/en/pressreleases',
    tier: 3, level: 'international', category: 'world',
    strategy: 'html', selector: 'h3.node__title a, .views-row h3 a, article h3 a',
    active: true,
  },
  {
    name: 'The New Humanitarian',
    url: 'https://www.thenewhumanitarian.org',
    pressPath: '',
    feedUrl: 'https://www.thenewhumanitarian.org/rss.xml',
    tier: 3, level: 'international', category: 'world',
    // Creative Commons licensed — free to use
    strategy: 'rss', selector: '',
    active: true,
  },

  // ── SPORT — Governing Bodies (Tier 2) ────────────────────────────────────────
  // Note: FIFA, UEFA, CAF, Olympics and World Athletics are JS-rendered SPAs.
  // active: false until headless-browser support is added to the fetcher.
  {
    name: 'FIFA',
    url: 'https://www.fifa.com',
    pressPath: '/en/news',
    tier: 2, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/en/news/"]',
    active: false,
  },
  {
    name: 'UEFA',
    url: 'https://www.uefa.com',
    pressPath: '/insideuefa/mediaservices/',
    tier: 2, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="news"]',
    active: false,
  },
  {
    name: 'CAF — Confederation of African Football',
    url: 'https://www.cafonline.com',
    pressPath: '/en/news/',
    tier: 2, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/en/news/"]',
    active: false,
  },
  {
    name: 'International Olympic Committee',
    url: 'https://olympics.com',
    pressPath: '/ioc/news',
    tier: 2, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/ioc/news/"]',
    active: false,
  },
  {
    name: 'World Athletics',
    url: 'https://worldathletics.org',
    pressPath: '/news',
    tier: 2, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/news/"]',
    active: false,
  },
  {
    name: 'Nigeria Football Federation',
    url: 'https://thenff.com',
    pressPath: '/news/',
    tier: 2, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'article h2 a, .entry-title a, h3 a',
    active: true,
  },

  // ── SPORT — Premier League Clubs (Tier 3) ────────────────────────────────────
  // Arsenal & Liverpool serve server-rendered HTML — confirmed working.
  // Chelsea, Man City, Tottenham are JS SPAs — active: false.
  {
    name: 'Arsenal FC',
    url: 'https://www.arsenal.com',
    pressPath: '/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a.responsive-card__wrapper',
    active: true,
  },
  {
    name: 'Liverpool FC',
    url: 'https://www.liverpoolfc.com',
    pressPath: '/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href^="/news/"]',
    active: true,
  },
  {
    name: 'Manchester United',
    url: 'https://www.manutd.com',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href^="/en/news/"]:not([href*="/listing/"])',
    active: true,
  },
  {
    name: 'Chelsea FC',
    url: 'https://www.chelseafc.com',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/article"]',
    active: false,
  },
  {
    name: 'Manchester City',
    url: 'https://www.mancity.com',
    pressPath: '/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/"]',
    active: false,
  },
  {
    name: 'Tottenham Hotspur',
    url: 'https://www.tottenhamhotspur.com',
    pressPath: '/news/',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/"]',
    active: false,
  },

  // ── SPORT — La Liga Clubs (Tier 3) ───────────────────────────────────────────
  // Barcelona serves server-rendered links. Real Madrid is a JS SPA.
  {
    name: 'FC Barcelona',
    url: 'https://www.fcbarcelona.com',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href^="/en/news/"]',
    active: true,
  },
  {
    name: 'Real Madrid CF',
    url: 'https://www.realmadrid.com',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/"]',
    active: false,
  },

  // ── SPORT — Bundesliga (Tier 3) ──────────────────────────────────────────────
  {
    name: 'FC Bayern Munich',
    url: 'https://fcbayern.com',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/en/news/"]',
    active: false,
  },

  // ── SPORT — Serie A (Tier 3) ─────────────────────────────────────────────────
  // Inter Milan confirmed server-rendered. Juventus & AC Milan are JS SPAs.
  {
    name: 'Inter Milan',
    url: 'https://www.inter.it',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href^="/en/news/"]',
    active: true,
  },
  {
    name: 'Juventus FC',
    url: 'https://www.juventus.com',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/articles/"]',
    active: false,
  },
  {
    name: 'AC Milan',
    url: 'https://www.acmilan.com',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/articles/"]',
    active: false,
  },

  // ── SPORT — Ligue 1 (Tier 3) ─────────────────────────────────────────────────
  {
    name: 'Paris Saint-Germain',
    url: 'https://www.psg.fr',
    pressPath: '/en/news',
    tier: 3, level: 'sport', category: 'sport',
    strategy: 'html', selector: 'a[href*="/news/"]',
    active: false,
  },
]

export function getAllSources(): Source[] {
  return sources
}

export function getSourcesByTier(tier: 1 | 2 | 3): Source[] {
  return sources.filter((s) => s.tier === tier && s.active)
}

export function getStats() {
  const active = sources.filter((s) => s.active)
  return {
    total: sources.length,
    active: active.length,
    tier1: active.filter((s) => s.tier === 1).length,
    tier2: active.filter((s) => s.tier === 2).length,
    tier3: active.filter((s) => s.tier === 3).length,
    byLevel: {
      federal:       active.filter((s) => s.level === 'federal').length,
      state:         active.filter((s) => s.level === 'state').length,
      ngo:           active.filter((s) => s.level === 'ngo').length,
      international: active.filter((s) => s.level === 'international').length,
      sport:         active.filter((s) => s.level === 'sport').length,
    },
  }
}
